- hosts: all
  tasks:
    - name: Qualify submitted tag
      ansible.builtin.command:
        cmd: just qualify
        chdir: "{{ zuul.project.src_dir }}"
      changed_when: false
    - name: Build independently versioned artifacts
      ansible.builtin.command:
        cmd: just build
        chdir: "{{ zuul.project.src_dir }}"
      changed_when: false
